### PR TITLE
Adding handling for extra slashes.  This closes #43

### LINKED ISSUE #43: Properties are not loaded correctly when searching for /META-INF
##### Issue Overview

While inside a Weld archive WAR file, the classloader used is unable to locate `/META-INF/somefile.properties`.

##### Expected Behaviour

Searching for `/META-INF/somefile.properties` and `META-INF/somefile.properties` should work fine.

##### Current Behaviour

Looking up `META-INF/somefile.properties` works, but having the leading `/` causes it to fail

##### Steps To Reproduce
1. See PR

### PR DESCRIPTION
**Pull request by johnament**
#### Short description of what this resolves:

This resolves #43 

#### Changes proposed in this pull request:

- Add a leading `/` to the `WEB-INF` base.  Remove the trailing `/`
- When adjusting the name, check if a `/` is present before appending

Fixes #43

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Travis build fixed with #45. Please update your PR so we can see green builds again :)

**Comment by bartoszmajsak** [comment]
@mkouba @tremes if you are fine with this PR I can take care of releasing the new version.

**Comment by johnament** [comment]
All green now.

**Comment by manovotn** [comment]
@bartoszmajsak if you would release it, that would be great :)
The next version could be another Beta or even a CR? Whatever you deem better.

**Comment by bartoszmajsak** [comment]
@manovotn I will, sure. Is there anything which holds us from `Final` though?

**Comment by manovotn** [comment]
@bartoszmajsak nothing I'd know of. We can make it Final.

**Comment by bartoszmajsak** [comment]
@manovotn can you point me to the Weld test suite? I did few minor tweaks on master and wanted to check myself if we are good with it so we can release `2.0.0.Final` tomorrow. I quickly skimmed through weld/core repo but couldn't easily find if that's the right thing.

**Comment by manovotn** [comment]
@bartoszmajsak just go to https://github.com/weld/core, change the version in [pom.xml](https://github.com/weld/core/blob/master/pom.xml#L44) and run `mvn clean install`. That should trigger a whole lot of tests using this container (TCK as well as our integration tests).

**Comment by bartoszmajsak** [comment]
It must have been too late yesterday and I simply missed that. All is looking fine.

> EDIT: Also, thumbs up for wanting to test the changes :)

We should automate it - changes in this lib should trigger tests in `core` and if all green make a release and then send PR. Need to think about it.

**Pull request merged**
