### PR TITLE
ARQ-2041 provide own CDIProvider

### PR DESCRIPTION
**Pull request by tremes**
This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian-container-weld/30)

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Related issue: https://issues.jboss.org/browse/ARQ-2041

Can you document why is it important and how to use it?

**Comment by johnament** [comment]
I can add a `ftest` module.  It'll actually help with my concerns for #29 .  This PR is important, if I'm understanding Martin, we run into an issue w/ Arquillian & Weld SE where stuff mostly works, but there's some caveats.  The class originally referenced is deprecated, and the configuration provided now will correctly use the newly implemented CDI provider.

So I'm +1 to bring this in, and would happily add the `ftest` module if Tomas doesn't have time.

**Comment by tremes** [comment]
This implementation of CDIProvider is necessary when you want to call `CDI.current()` in your code and there is already test (https://github.com/arquillian/arquillian-container-weld/blob/master/src/test/java/org/jboss/arquillian/container/weld/embedded/WeldEmbeddedCDIProviderTest.java) for this. So this is basically internal stuff of this container.
Any suggestions where I should document it? I am not sure what do you want to add to this `ftest` module (sounds like functional tests) so you can share your ideas guys. :-)

**Comment by johnament** [comment]
`ftests` usually serve as demos to show how a user may use it.  Its not really relevant here, since you're basically fixing some broken behavior, e.g. the current container assumes to be a WAR file when it actually may not be.

**Comment by bartoszmajsak** [comment]
Then I misunderstood. I thought that by introducing this SPI we are opening up for extensions.

`ftest` (functional tests) are not necessarily simple examples - they are obviously demonstrating how to use given functionality, but also verify that stuff works end-to-end.

**Comment by tremes** [comment]
Ok. So I think `ftest` module doesn't make sense here. @johnament is https://github.com/arquillian/arquillian-container-weld/pull/31 really needed then?

**Comment by johnament** [comment]
Yes, absolutely #31 is needed.  If you think we should have a separate ticket for better test strategies, thats fine.  We should have some end to end tests against the running container that make sure its working as expected and supports an appropriate level of functionality.

**Pull request merged**
