### PR TITLE
[ARQ-1255] Multiple deployment support in Weld SE embedded

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by johnament** [comment]
This change has some very clear copy/paste files.  Any chance you can introduce a common module?

**Comment by astefanutti** [comment]
@johnament you're right. That being said, that's the pattern that's been used for `weld-se-embedded-1` and `weld-se-embedded-1.1` with root package renaming. I've just fit into that existing integration for that new `weld-se-embedded-2.1` module though consistency is not a good reason for code duplication. But I'd like to have the opinion of the original authors / maintainers for the `weld-se-embedded-1.*` modules because it may not be worth the effort / the extra module for Weld SE. Indeed in SE, older versions of CDI may become obsolete more rapidly than in EE.

**Comment by aslakknutsen** [comment]
Technically these should be able to be pulled into a se-common module:

* ContextClassLoaderManager
* ShrinkwrapBeanDeploymentArchive
* ShrinkwrapBeanDeploymentArchiveImpl
* WasCalledExtension
* ShrinkwrapBeanDeploymentArchiveTestCase
* WeldSEConfiguration

**Comment by astefanutti** [comment]
@aslakknutsen thanks. I'll refactor it ASAP.

**Comment by johnament** [comment]
Let me know if I can help provide the basics.

**Comment by johnament** [comment]
@aslakknutsen for the test classes... create a test-jar?

**Comment by aslakknutsen** [comment]
@johnament Yea, the Tests can live in common, but be included to run in the other modules as a test-jar; https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#dependenciesToScan

**Comment by johnament** [comment]
So there's an interesting problem.

Even though these classes are named similarly, they're different enough that there's a problem.  I'm wondering, can the Weld 1.0 container be dropped? As far as I know, no one should be using that version range of weld any longer.

If we can do that, then splitting out se-common becomes clean.  If not, then Weld SE 1.0 will need its own private copies.

**Comment by aslakknutsen** [comment]
Eventually Weld 1.x will be dropped.

Any thoughts on how different Weld 3 will be from Weld 2? If we' end up with se-common-2 and a se-common-3 then the point kinda dies.

**Comment by astefanutti** [comment]
@johnament, @aslakknutsen, I finally find the time to look at it.

I've just created a common `arquillian-weld-se-embedded` module that factorises the Weld SE adapters classes and tests.

Let me know if that's what you had in mind and if you have any feedback before eventually merging the PR.

**Comment by johnament** [comment]
@astefanutti @aslakknutsen sounds about right to me.  Current weld 2.3 bootstrap matches weld 3.  I wonder if it makes sense to deprecate everything prior to weld 2.3.

**Comment by astefanutti** [comment]
@johnament yes. Java EE 6 is based on CDI 1.0 / Weld 1.1 and still around. So maybe that can wait a little. I don't have any strong opinion on it. Let me know.

Once we're good, let me know if I can help for releasing a new version of the adapter.

**Comment by antoinesd** [comment]
@astefanutti @aslakknutsen @johnament I'm strongly against deprecating Weld 1.1 in this version of the adapter. Major Java EE 6 server still use it: JBoss EAP 6.x or Oracle Weblogic 12 to start with. Perhaps it's time to release a version 1.0.0-Final of this adapter and start a version 2 which will drop CDI 1.0 support ?

**Pull request closed without merging**
