### PR TITLE
ARQ-2048: Excluded elements in beans.xml by the Weld Arquillian plugi…

### PR DESCRIPTION
**Pull request by astefanutti**
…n is an all check instead of an any

### CODE REVIEW

**Comment by tremes** [comment]
I think we should definitely add some test for excluding some bean/s because I think we don't have any. Not really sure why I didn't include one when I was fixing the original issue. 

I'll try to add some test.

**Comment by astefanutti** [comment]
@tremes Thanks for the merge. I agree with you that some tests would be worth the effort. I'll try to find some time ASAP.

**Comment by tremes** [comment]
@astefanutti you're more than welcome.:-) I already introduced some basic one. Feel free to expand it.

**Comment by astefanutti** [comment]
Ah I've just seen you pushed @cba0c735adff9c9b0defb9d5e05d426c2573baf2. Awesome!

**Pull request merged**
